version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: soobo-mongo-dev
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=soobo-mbti
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - soobo-network

  soobo-mbti-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: soobo-mbti-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=mongodb://soobo_user:soobo_password_dev@mongodb:27017/soobo-mbti?authSource=soobo-mbti
      - MONGODB_USER=soobo_user
      - MONGODB_PASSWORD=soobo_password_dev
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:8080,http://127.0.0.1:8080,file://
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=1000
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - soobo-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongodb_data_dev:

networks:
  soobo-network:
    driver: bridge
